[workspace]
resolver = "2"
members = [
  "crates/api",
  "crates/holographic-viewer",
  "crates/hypc",
  "crates/link_emulator",
  "crates/obj2hypc",
  "crates/sim_agent",
  "crates/sim_orchestrator",
]

[workspace.package]
edition = "2021"
license = "MIT"
