[package]
name = "api"
version = "0.1.0"
edition = "2021"

[dependencies]
bytes = "1"
prost = "0.13"
tonic = { version = "0.12", features = ["transport"] }

[build-dependencies]
tonic-build = "0.12"
prost-build = "0.13"

[features]
default = []
